type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/nature/RocksEarthAtlas.png"
normal_map_texture="/textures/material_overrides/nature/RocksEarthAtlas_N.png"
metallic=0.4
perceptual_roughness= 0.9 
uv_transform = {  texture_subset_dimensions = { offset = [512,0], dimensions = [512, 512], base_texture_dimensions = [2048,2048] } }

[material.extension]

[material.extension.custom_uniforms]
uv_input_scale= 8.0 
use_fixed_world_uv = 1
 
