type = "MagicFxMaterial"

[material.base]  
base_color = { LinearRgba = [1.0,1.0,1.0,1.0] }
emissive= [1.0,1.0,1.0,30.6]   
double_sided= true
alpha_mode=  "Blend"               



[material.extension]
base_color_texture = "/textures/vfx_textures/fx_fireskill/fire_loop_sheet.png"

[material.extension.custom_uniforms]
scroll_repeats = [1.0,1.0]
scroll_speed = [8.0,0.0]
distortion_amount = 0.02
distortion_speed = [0.04,0.04]
animation_frame_dimension = [4,4]