 




type = "DoodadMaterial"


[material.base]  
base_color_texture="/textures/material_overrides/marble_diffuse.png"
normal_map_texture="/textures/material_overrides/slate_2_normal.png"
perceptual_roughness= 0.9
metallic=0.4
 


[material.extension]



[material.extension.custom_uniforms]
use_fixed_world_uv = 1


[properties]
uv_scale_factor= 1.0 
