type = "DoodadMaterial"


[material.base]  
base_color_texture="/textures/material_overrides/academy/AcademyAtlas.png"
normal_map_texture="/textures/material_overrides/academy/AcademyAtlas_N.png"
perceptual_roughness= 0.9
metallic=0.4
uv_transform = {  texture_subset_dimensions = { offset = [1024,0], dimensions = [512, 512], base_texture_dimensions = [2048,2048] } }


[material.extension]



[material.extension.custom_uniforms]
use_fixed_world_uv = 1
uv_input_scale= 4.0 
 