type = "DoodadMaterial"


[material.base]  
base_color_texture="/textures/material_overrides/slate_1_diffuse.png"
normal_map_texture="/textures/material_overrides/slate_1_normal.png"
perceptual_roughness= 0.9
base_color={ LinearRgba = [0.15, 0.15, 0.15, 1.0] }

[properties]
uv_scale_factor= 1.0 
 