type = "DoodadMaterial"


[material.base]  
base_color_texture="/textures/material_overrides/rocks2_diffuse.png"
normal_map_texture="/textures/material_overrides/rocks2_normal.png"
perceptual_roughness= 0.9
metallic = 0.4

[properties]
uv_scale_factor= 1.0 
 