type = "DoodadMaterial"


[material.base]  
base_color_texture="/textures/material_overrides/stone_wall_diffuse.png"
normal_map_texture="/textures/material_overrides/stone_wall_normal.png"
perceptual_roughness= 0.8


[properties]
uv_scale_factor= 1.0 
 