type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/human/plaster_wall_D.png"
normal_map_texture="/textures/material_overrides/human/plaster_wall_N.png"
perceptual_roughness=0.9
metallic=0.4

[material.extension]

[material.extension.custom_uniforms]
use_fixed_world_uv = 1

[properties]
uv_scale_factor=1.0