type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/elven/PolygonElven_Texture_01_B.png"
perceptual_roughness= 0.9 

[material.extension.custom_uniforms]
uv_input_scale= 1.0 
 
 
