type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/treetrunk1_diffuse.png"
perceptual_roughness=0.8
metallic=0.4
base_color={ LinearRgba = [0.6, 0.4, 0.2, 1.0] }

[material.extension]

[material.extension.custom_uniforms]

[properties]
uv_scale_factor=1.0