type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/leaves3_diffuse.png"
perceptual_roughness=0.8
metallic=0.4
base_color={ LinearRgba = [0.2, 0.8, 0.2, 1.0] }

[material.extension]

[material.extension.custom_uniforms]
uv_input_scale= 1.0 