type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/ornate_tiles_2_diffuse.png"
normal_map_texture="/textures/material_overrides/ornate_tiles_2_normal.png"
perceptual_roughness=0.8
metallic=0.4

[material.extension]

[material.extension.custom_uniforms]

[properties]
uv_input_scale=1.0