type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/MCastle_ColorAtlas_01.tga"
perceptual_roughness=0.8

[material.extension]

[material.extension.custom_uniforms]
uv_input_scale= 1.0