type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/rock_magic_dark.png"
normal_map_texture="/textures/material_overrides/rocks1_normal.png"
perceptual_roughness=0.8 

[material.extension]

[material.extension.custom_uniforms]
use_fixed_world_uv = 1
blank_top_bottom = 1 

[properties]
uv_scale_factor=1.0