type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/rocks2_diffuse.png"
normal_map_texture="/textures/material_overrides/rocks2_normal.png"
perceptual_roughness=0.8
metallic=0.4


[material.extension]
mask= "/textures/cel_mask.png"


[material.extension.custom_uniforms]
uv_input_scale= 1.0 
