type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/stone_wall_3_diffuse.png"
normal_map_texture="/textures/material_overrides/stone_wall_3_normal.png"
perceptual_roughness=0.8
metallic=0.4

[material.extension]

[material.extension.custom_uniforms]

[properties]
uv_scale_factor=1.0