type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/toonstone_diffuse.png"
normal_map_texture="/textures/material_overrides/toonstone_normal.png"
perceptual_roughness=0.8
metallic=0.4

[material.extension]

[material.extension.custom_uniforms]
uv_input_scale= 4.0 
 