type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/wall2_diffuse.png"
normal_map_texture="/textures/material_overrides/wall2_normal.png"
perceptual_roughness=1.0
metallic=0.4
base_color={ LinearRgba = [1.0, 1.0, 1.0, 1.0] }

[material.extension]

[material.extension.custom_uniforms]

[properties]
uv_scale_factor=1.0