type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/dark_elven/House Walls A_House_Walls_Wood_Dark_A_AlbedoTransparency.png"
normal_map_texture="/textures/material_overrides/dark_elven/House Walls A_House_Walls_Wood_Dark_A_Normal.png"
perceptual_roughness=0.8
base_color = { LinearRgba = [0.42, 0.42, 0.42, 1.0] }

[material.extension]

[material.extension.custom_uniforms]
use_fixed_world_uv = 1

[properties]
uv_scale_factor=1.0