type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/dark_elven/Tile-able Plane A_Tree_Bark_1B1_AlbedoTransparency2.png"
normal_map_texture="/textures/material_overrides/dark_elven/Tile-able Plane A_Tree_Bark_1B1_Normal.png"
perceptual_roughness=0.8
base_color = { LinearRgba = [0.6, 0.6, 0.6, 1.0] }

[material.extension]

[material.extension.custom_uniforms]
use_fixed_world_uv = 1

[properties]
uv_scale_factor=1.0