type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/dark_elven/ruins_foliage.png"
perceptual_roughness=0.8
alpha_mode="Blend"

[material.extension]

[material.extension.custom_uniforms]
use_fixed_world_uv = 1
uv_input_scale= 4.0 