type = "DoodadMaterial"

[material.base]  
perceptual_roughness=0.4
metallic=1.0
base_color = { LinearRgba = [1.0, 1.0, 1.0, 1.0] }

[material.extension]

[material.extension.custom_uniforms]
use_fixed_world_uv = 1

[properties]
uv_scale_factor=1.0