type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/medieval_village/T_Wall1_D_2k.png"
normal_map_texture="/textures/material_overrides/medieval_village/T_Wall1_N_2k.png"
perceptual_roughness=0.8
metallic=0.4

[material.extension]

[material.extension.custom_uniforms]
use_fixed_world_uv = 1
uv_input_scale= 4.0 