type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/castle/MCastle_ColorAtlas_01.tga" 
base_color = { LinearRgba = [1.0,1.0,1.0,1.0] }
perceptual_roughness= 0.9 
          

[material.extension.custom_uniforms]
uv_input_scale= 1.0 
 