type = "DoodadMaterial"


[material.base]  
base_color_texture="/textures/material_overrides/pixel/overgrown_pixel_dungeon.png"
normal_map_texture="/textures/material_overrides/pixel/overgrown_pixel_dungeon_normal.png"
base_color = { LinearRgba = [0.33,0.33,0.33,1.0] }
perceptual_roughness= 0.9
uv_transform = {  texture_subset_dimensions = { offset = [64,64], dimensions = [32, 32], base_texture_dimensions = [352,272] } }

[material.extension.custom_uniforms]
use_fixed_world_uv = 1
uv_input_scale= 4.0  
