type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/pixel/szadiart_catacombs.png"
normal_map_texture="/textures/material_overrides/pixel/szadiart_catacombs_normal.png"
perceptual_roughness= 0.9
uv_transform = {  texture_subset_dimensions = { offset = [0,176], dimensions = [32, 32], base_texture_dimensions = [1024,640] } }

[material.extension.custom_uniforms]
uv_input_scale= 1.0 