type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/weapons/dungeon_weapons_albedo_sm.png"
perceptual_roughness=0.9
metallic=0.0

[material.extension]

[material.extension.custom_uniforms]
use_fixed_world_uv = 1
uv_input_scale= 4.0 