type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/pixel/cainos/cainos_dungeon.png"
perceptual_roughness= 0.9

[material.extension.custom_uniforms]
uv_input_scale= 1.0 
 
 
