type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/pixel/pixel_foliage.png"
perceptual_roughness= 0.9
double_sided= true
alpha_mode=   { Mask = 0.2 }

[material.extension.custom_uniforms]
uv_input_scale= 1.0 
 
 