type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/fern1_diffuse.png"
perceptual_roughness=0.8
metallic=0.4
double_sided= true
alpha_mode=  {Mask = 0.5 }        

[material.extension]

[material.extension.custom_uniforms]
uv_input_scale= 1.0 