type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/nature/MeadowFoliageAtlas.png" 
base_color = { LinearRgba = [0.22,0.45,0.15,1.0] }
perceptual_roughness= 0.9 
uv_transform = {  texture_subset_dimensions = { offset = [0,512], dimensions = [512, 512], base_texture_dimensions = [2048,2048] } }
double_sided= true
alpha_mode=  {Mask = 0.5 }        
 

[material.extension.custom_uniforms]
uv_input_scale= 1.0
 
