type = "DoodadMaterial"


[material.base]  
base_color_texture="/textures/material_overrides/pixel/overgrown_pixel_dungeon.png"
normal_map_texture="/textures/material_overrides/pixel/overgrown_pixel_dungeon_normal.png"
perceptual_roughness= 0.9
uv_transform = {  texture_subset_dimensions = { offset = [64,64], dimensions = [32, 32], base_texture_dimensions = [352,272] } }

[properties]
uv_scale_factor= 1.0 

