type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/pixel/pixel_foliage.png"
perceptual_roughness= 0.9
double_sided= true
alpha_mode=   { Mask = 0.2 }

[properties]
uv_scale_factor= 1.0 
 
 