type = "DoodadMaterial"


[material.base]  
base_color_texture="/textures/material_overrides/pixel/szadiart_catacombs.png"
normal_map_texture="/textures/material_overrides/pixel/szadiart_catacombs_normal.png"
perceptual_roughness= 0.9
uv_transform = {  texture_subset_dimensions = { offset = [64,240], dimensions = [32, 32], base_texture_dimensions = [1024,640] } }

[properties]
uv_scale_factor= 1.0 