type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/dreamscape_castle/building/T_CastleSlabs_Unity_C.png"
normal_map_texture="/textures/material_overrides/dreamscape_castle/building/T_CastleSlabs_Unity_N.png"
perceptual_roughness=0.8
metallic=0.4

[material.extension]

[material.extension.custom_uniforms]
use_fixed_world_uv = 1

[properties]
uv_scale_factor=1.0