type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/castle/CastleAtlas.png" 
base_color = { LinearRgba = [1.0,1.0,1.0,1.0] }
perceptual_roughness= 0.9 
uv_transform = {  texture_subset_dimensions = { offset = [1536,0], dimensions = [512, 512], base_texture_dimensions = [2048,2048] } }
          

[material.extension.custom_uniforms]
uv_input_scale= 4.0 
use_fixed_world_uv = 1
 