
type = "DoodadMaterial"


[material.base]  
base_color_texture="/textures/material_overrides/cave/Tex_CavePack_ground_a.png"
normal_map_texture="/textures/material_overrides/cave/Tex_CavePack_ground_n.png"
perceptual_roughness= 0.8
metallic=0.4
 


[material.extension]



[material.extension.custom_uniforms]


[properties]
uv_scale_factor= 1.0 