type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/cliff4_diffuse.png"
normal_map_texture="/textures/material_overrides/cliff4_normal.png"
perceptual_roughness=0.8
metallic=0.4
base_color={ LinearRgba = [1.0, 1.0, 1.0, 1.0] }

[material.extension]

[material.extension.custom_uniforms]
uv_input_scale= 4.0 