type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/cliff5_diffuse.png"
normal_map_texture="/textures/material_overrides/cliff5_normal.png"
perceptual_roughness=0.8
metallic=0.4
base_color={ LinearRgba = [0.34, 0.62, 0.75, 1.0] }

[material.extension]

[material.extension.custom_uniforms]
uv_input_scale= 4.0 