type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/nature/MeadowFoliageAtlas.png" 
base_color = { LinearRgba = [0.18,0.12,0.10,1.0] }
perceptual_roughness= 0.9 
uv_transform = {  texture_subset_dimensions = { offset = [0,1536], dimensions = [512, 512], base_texture_dimensions = [2048,2048] } }
          

[material.extension.custom_uniforms]
uv_input_scale= 2.0 
use_fixed_world_uv = 1
 
