type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/human/wood_floor_square_D.png"
normal_map_texture="/textures/material_overrides/human/wood_floor_square_N.png"
perceptual_roughness=0.9
metallic=0.4

[material.extension]

[material.extension.custom_uniforms]
uv_input_scale= 4.0 