type = "DoodadMaterial"

[material.base]  
base_color_texture="/textures/material_overrides/cobbles2_diffuse.png"
normal_map_texture="/textures/material_overrides/cobbles2_normal.png"
base_color = { LinearRgba = [0.7, 0.7, 0.7, 1.0] }
perceptual_roughness=0.9
metallic=0.4

[material.extension]

[material.extension.custom_uniforms]
use_fixed_world_uv = 1
uv_input_scale= 4.0 